name: Update GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "k4pub2users2.html"

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git Identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Copy and rename file
        run: |
          git fetch origin docs
          git checkout docs
          git checkout main -- k4-pub-users2.html
          mv k4-pub-users2.html index.html
          git add index.html
          git commit -m "Update index.html from main"
          git push origin docs
